import type { Metadata } from "next";
import "./globals.css";


const name = "Next.js Practice"
export const siteTitle = "Next.js blog"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <img src="/images/profile.png" />
          <h1>{name}</h1>
        </header>
      </body>
    </html>
  );
}
